[project]
name = "fastapi-single-process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gio Abeleda", email = "gioabeleda@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
fastapi-single-process = "fastapi_single_process:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
